Flight search screen responsive design
ayowoleadenuga/nkeji-web pull request #7
Opened 2024-08-13 11:47 UTC by ELIJAHJOHNNY

2024-08-17 02:20 UTC, ayowoleadenuga commented on src/components/Homepage/components/navigation.tsx
> +  const { first_name, last_name } = user!;
This will lead to errors as the initial state for `user` is null.

2024-08-17 02:21 UTC, ayowoleadenuga commented on src/components/Homepage/components/navigation.tsx
> +            <AvatarFallback>{`${first_name[0]}${last_name[0]}`}</AvatarFallback>
In line with the comment above
```suggestion
            <AvatarFallback>{`${user.first_name[0]}${user.last_name[0]}`}</AvatarFallback>
```

2024-08-17 02:45 UTC, ayowoleadenuga requested changes
Nice work chief! well done. Just a few observations
1. The top part of the header seems to 'white' out as seen in the image below
<img width="817" alt="image" src="https://github.com/user-attachments/assets/0a76aa3b-4f38-4c34-9c1a-0430fb31a97c">

2. Can we reduce the white space between the top header here and the 'select flight'. See figma
<img width="688" alt="image" src="https://github.com/user-attachments/assets/ea0afa0c-075e-41cd-bf84-7b08a3201b34">

3. I noticed that some of the fonts are no longer 'sans-serif'

4. I think the reason for the issue in my comment 2 above is because the panel is not rendered on mobile
<img width="827" alt="image" src="https://github.com/user-attachments/assets/3cc74700-4af2-499c-8bc9-96a0fce522c5">

2024-08-20 11:49 UTC, ELIJAHJOHNNY commented on src/components/Homepage/components/navigation.tsx
> +            <AvatarFallback>{`${first_name[0]}${last_name[0]}`}</AvatarFallback>
Okay. Thank you.. This has been catered for

2024-08-20 11:50 UTC, ELIJAHJOHNNY commented
The responsiveness issues pointed out have been rectified. Thank you

2024-08-23 17:01 UTC, ayowoleadenuga approved these changes

2024-08-23 17:02 UTC, merged